default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: true)
    increment_build_number(xcodeproj: "LoopApp.xcodeproj")
    build_app(
      workspace: "LoopApp.xcworkspace",
      scheme: "LoopApp",
      export_method: "app-store"
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Promote build to App Store"
  lane :release do
    match(type: "appstore", readonly: true)
    build_app(
      workspace: "LoopApp.xcworkspace",
      scheme: "LoopApp",
      export_method: "app-store"
    )
    upload_to_app_store(force: true)
  end
end
